### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Raddad10** [Optimization-AI/ICCV2021_DeepAUC#1]
please give use your best weights

**Comment by Raddad10** [comment]
how can we train all labels ?

**Comment by yzhuoning** [comment]
We currently focus on the binary classification. In other word, you can pretrain the models by multi-label setting and then use pretrained weights to re-train the model on each label using AUCM loss. You can take a look at this [example](https://github.com/Optimization-AI/LibAUC/blob/main/examples/05_Optimizing_AUROC_Loss_with_DenseNet121_on_CheXpert.ipynb).
